spring:
  datasource:
    url: jdbc:mysql://localhost:3306/distance
    username: distance
    password:
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 50mb
      max-request-size: 50mb
server:
  port: 8086

alisms:
  product: Dysmsapi
  domain: dysmsapi.aliyuncs.com
  accessKeyId: 123
  accessKeySecret: 123
  signName: 123
  templateCode: SMS_123